spring:
  application:
    name: SocialMultiplication
  datasource:
    url: jdbc:mysql://localhost:3306/amigoscode?allowPublicKeyRetrieval=true&useSSL=false
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
